### ISSUE TITLE
Slower execution of latest macOS builds

### ISSUE THREAD

**Issue by jyppy** [Venafi/vcert#143]
**PROBLEM SUMMARY**
latest (v4-11.0-1092 & v4.10) of the MacOS builds are slower that prior versions (ie v4.9.5+873)

Its worth noting that the older build report higher CPU / lower execution time

**STEPS TO REPRODUCE**
On the same machine with 4 vcert binary side by side:

❯ time /usr/local/bin/vcert-v4.9.5+873 -v
vcert-v4.9.5+873 version v4.9.5+873
/usr/local/bin/vcert-v4.9.5+873 -v  0.01s user 0.00s system **76%** cpu 0.010 total
❯
❯
❯ time /usr/local/bin/vcert-v4.9.6+895_darwin -v
vcert-v4.9.6+895_darwin version v4.9.6+895
/usr/local/bin/vcert-v4.9.6+895_darwin -v  0.01s user 0.00s system **82%** cpu 0.009 total
❯
❯
❯ time /usr/local/bin/vcert-v4.10.0+1023_darwin -v
vcert-v4.10.0+1023_darwin version v4.10.0+1023
/usr/local/bin/vcert-v4.10.0+1023_darwin -v  0.01s user 0.00s system 0% cpu **5.027** total
❯
❯
❯ time /usr/local/bin/vcert-v4.11.0+1092_darwin -v
vcert-v4.11.0+1092_darwin version v4.11.0+1092
/usr/local/bin/vcert-v4.11.0+1092_darwin -v  0.01s user 0.00s system 0% cpu **5.025** total
❯

**EXPECTED RESULTS**
I'd expect similar response time. it looks like a 5sec delay is added with the latest builds
**ACTUAL RESULTS**

![image](https://user-images.githubusercontent.com/755543/99329486-753b5d00-28d2-11eb-9fda-0caefcfde633.png)

**ENVIRONMENT DETAILS**
In this scenario, no Venafi server, just the CLI on MacOS v 10.15.7

**COMMENTS/WORKAROUNDS**

**Comment by marcos-albornoz** [comment]
hi @jyppy,

I was testing the behavior the latest two days using different versions... resulting that, at the same way like you, the issue is not reproducible in the released version vcert-4.9.6+895 and prior to that, but I was able to reproduce it starting on vcert-4.9.7+945 following the next versions.
But today I've tried again to reproduce it, and simply I'm not able to reproduce with any version :-(.
It's important to mention that when I was able to reproduce it at the past two days... the issue was intermittent... that is one time of each 3 times I was able to reproduce it.
So in order to try to find the root case of this behavior, can you share the specifications of hardware of your Mac?, also can you confirm if is it still reproducible in your Mac now? and if is that consistently reproducible?

P.S. The issue was tried to reproduce in other 3 Mac machines but it was not possible to reproduce it.
The specifications of my Mac are:
* macOS High Sierra(10.13.6)
* MacBook Pro (Retina, 15-inch, Mid 2015)
* Processor 2.2 GHz Intel Core i7
* Memory 16 GB 1600 MHz DDR3

**Comment by jyppy** [comment]
This was on a 

- macOS Catalina (10.15.7)

- MacBook Pro (15-inch, 2018)

- 2.9 GHz 6-Core Intel Core i9

- 32 GB 2400 MHz DDR4

I also noticed the same problem on another mac, yet a 3rd mac did not show this issue.
On the mac I use daily, the problem is consistent but disappears if I disconnect the network!! There must be a network call made at the start of the execution of the vcert CLI

**Comment by jyppy** [comment]
After further investigation, I see that starting vcert  triggers a DNS resolution (DNS A and AAAA records for venafi.com).

After resetting the network configuration, the 5 sec delay was gone... odd behavior considering v4.9 and below did not experience such issue.

**Comment by tr1ck3r** [comment]
Pretty sure that is from the code we added to get VCert's primary IP address for the _Source Application Tagging_ feature.  My understanding was that it wasn't actually supposed to attempt any DNS query but apparently it does.  Perhaps the team can find another way to do it.

https://github.com/Venafi/vcert/blob/a9d2e79f7d5ce5813b13f1ad6010d848442d31ea/pkg/endpoint/endpoint.go#L439-L446

**Comment by marcos-albornoz** [comment]
Thanks @jyppy and @tr1ck3r for your detailed comments.

I've considered the scenario where @jyppy detected the delay is happening, so I've experimented the following:

1. Being connected to the Venafi vpn, I've run the vcert versions 4.9.6, 4.9.7 and 4.10. The issue doesn't happen.
2. I've disconnected to the Venafi vpn, then I've repeated the tests. The issue is now reproducible starting on 4.9.7; in prior versions the issue doesn't happen.
3. I've re-connected  to the Venafi vpn, then again I've repeated the tests. The issue is not reproducible in any vcert version.

I've done another set of tests: being disconnected of the Venafi vpn, that is the scenario where the issue happens, I've turned off my wifi( that is my one way to access to internet) and then I've repeated the tests resulting that the issue doesn't happen; then I've turned on again the wifi and the issue is now reproducible.

The curious thing is that I've made a local build of vcert in my Mac containing the changes labeled for 4.9.7(even the changes mentioned by @tr1ck3r) resulting that the issue is not reproducible with that local build in any of the scenarios where I'm able to reproduce it using the versions in https://github.com/Venafi/vcert/releases/

**Comment by marcos-albornoz** [comment]
Hi @jyppy,

According with the @tr1ck3r suggestions, we created the [pre-release v4.11.2](https://github.com/Venafi/vcert/releases/tag/v4.11.2) which is including the suggested change.

Can you please test it and let us know if that is fixing the issue?

**Comment by jyppy** [comment]
@marcos-albornoz @tr1ck3r  
Just tested v4.11.2 and it looks like the lag has now gone.
Thanks for that.
