### ISSUE TITLE
`endpoint` package changes global logger prefix

### ISSUE THREAD

**Issue by orlangure** [Venafi/vcert#161]
**PROBLEM SUMMARY**

`endpoint` package changes `log` prefix globally:
https://github.com/Venafi/vcert/blob/f9694dc8b7fd8ba9ca16e41d50cf918305bcdb17/pkg/endpoint/endpoint.go#L50-L53

**STEPS TO REPRODUCE**

Import `endpoint` package externally and use `log.Println("something")`, see that it has `vCert:` prefix...

**EXPECTED RESULTS**
I would expect that the library won't change output of my unrelated logs.

**ACTUAL RESULTS**

`vCert` prefix appears in logs.

**ENVIRONMENT DETAILS**

**COMMENTS/WORKAROUNDS**

**Comment by tr1ck3r** [comment]
Thank you for raising this concern, @orlangure, I agree with you that the behavior you described is undesirable and was not intentional.  We will look into refactoring so that the log prefix isn't applied globally.

https://stackoverflow.com/questions/24728925/does-the-logger-setprefix-stick-between-channels-threads-as-a-context
