### ISSUE TITLE
CustomFields are not supported with ImportCertificate

### ISSUE THREAD

**Issue by maelvls** [Venafi/vcert#187]
I use the [`ImportCertificate`](https://github.com/Venafi/vcert/blob/0645745c0c8c5800811b5a6b200cfb9bef30a32a/pkg/endpoint/endpoint.go#L92-L93) function with the latest version of vcert (v4.15.2, 171269e) to import certificates into TPP. I wish to add "custom fields" to the certificates in order to identify them (also called "Attributes" in the "Support" tab in Venafi TPP).

My call to `ImportCertificate` looks like this:

```go
tpp.ImportCertificate(&ImportRequest{
	// ...
	CustomFields: []certificate.CustomField{
		{Type: certificate.CustomFieldOrigin, Value: "my-tool"},
		{Type: certificate.CustomFieldPlain, Name: "Cluster", Value: "foo"},
	}
})
```

It seems like only the Origin field gets added to TPP. The other "plain" fields don't.

Under the hood, `ImportCertificate` does 4 HTTP requests:

![Screenshot from 2021-11-09 14-33-31](https://user-images.githubusercontent.com/2195781/140933717-b296a387-496c-4ce6-b683-d2397f8610e6.png)

The last one is the faulty one. As you can see, only the Origin field is set:

![Screenshot from 2021-11-09 14-33-47](https://user-images.githubusercontent.com/2195781/140933711-6a9fe4bb-edee-4ab3-839f-e109b9817ce9.png)

**Comment by maelvls** [comment]
Digging into vcert, it seems like the TPP implementation of `ImportCertificate` discards any custom field that has not the Origin type:

https://github.com/Venafi/vcert/blob/0645745c0c8c5800811b5a6b200cfb9bef30a32a/pkg/venafi/tpp/connector.go#L1253-L1258

Is that intended?

**Comment by tr1ck3r** [comment]
@maelvls Yes, you're right this would be an enhancement.  We've actually never previously had anyone express interest in Custom Field support for the import use case and since TPP currently lacks that support in the `POST /vedsdk/certificates/import` [API endpoint](https://docs.venafi.com/Docs/21.3SDK/TopNav/Content/SDK/WebSDK/r-SDK-POST-Certificates-Import.php) adding it would be quite expensive from the standpoint of the number of API calls required. Since Custom Fields in TPP can be applied by policy (and inherited by certificates) and import typically targets a single policy folder (zone), I suspect that is how customers have been getting the Custom Field assignments if they require it.

**Comment by tr1ck3r** [comment]
Added https://community.venafi.com/ideas/custom-field-support-for-post-vedsdk-certificates-import-1017

**Comment by maelvls** [comment]
Thanks for creating this feature request in community.venafi.com/ideas! Unfortunately, I don't have access to it :disappointed: Do you think this link can be accessed by the community?

**Comment by tr1ck3r** [comment]
The link should be accessible to all current Venafi customers.  It has not yet been opened up to all internal departments but I believe that is the end goal.
