### ISSUE TITLE
Setting CA Template as a parameter

### ISSUE THREAD

**Issue by antfok** [Venafi/vcert#230]
**BUSINESS PROBLEM**
Presently, the CA Template is locked to the policy folder, but what if the Application using vcert can have more than one choice of CA Template. And creating a lot of folders to account for all possibilities can become cumbersome for larger customers and requiring extra work. This is available today via CADN if using Certificates/Request

**PROPOSED SOLUTION**
Have something similar to CADN where optionally they can request the cert along with providing the CA Template info. 

**CURRENT ALTERNATIVES**
Create a new folder with the CA Template.

**VENAFI EXPERIENCE**

**Comment by tr1ck3r** [comment]
@antfok VCert CLI already supports per request specification of a CA template for Trust Protection Platform using the `--ca-dn` hidden parameter.  We've intentionally chosen not to document this parameter because using it is counter to security best practice which is for the issuing certificate authority to be enforced by policy and because using it makes for a generally poorer user experience.
